<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service.proto

namespace App\Proto;

class Service
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a7c0a0d736572766963652e70726f746f120361707022160a074d657373616765120b0a036d7367180120012809322c0a044563686f12240a0450696e67120c2e6170702e4d6573736167651a0c2e6170702e4d65737361676522004218ca02094170705c50726f746fe202094170705c50726f746f620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

